# Nixpacks configuration for Railway
[phases.build]
  cmds = [
    "cd src/SecurityGuardPlatform.API",
    "dotnet restore",
    "dotnet publish -c Release -o /app/out"
  ]

[phases.start]
  cmd = "dotnet /app/out/SecurityGuardPlatform.API.dll"

[variables]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
